# Generated by Django 2.0.3 on 2018-03-13 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplaceNum', models.CharField(max_length=6)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('phone', models.CharField(max_length=6)),
                ('login', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
