# Generated by Django 2.0.3 on 2018-03-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workplace',
            new_name='Workspace',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='workplaceNum',
            new_name='workspaceNum',
        ),
    ]
