# Generated by Django 2.0.3 on 2018-03-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20180313_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
