# Generated by Django 2.0.3 on 2018-03-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='xPos',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='yPos',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
