# Generated by Django 2.0.3 on 2018-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0005_auto_20180313_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='stage',
            field=models.CharField(choices=[('NA', 'Неизвестно'), ('1R', 'Первый этаж правое крыло'), ('1L', 'Первый этаж левое крыло'), ('2R', 'Второй этаж правое крыло'), ('2L', 'Второй этаж левое крыло')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='login',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='phone',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspaceNum',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
