# Generated by Django 2.0.3 on 2018-04-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0006_auto_20180318_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='workspace',
            name='stage',
            field=models.CharField(choices=[('__', 'Неизвестно'), ('1R', 'Первый этаж правое крыло'), ('1L', 'Первый этаж левое крыло'), ('2R', 'Второй этаж правое крыло'), ('2L', 'Второй этаж левое крыло')], default='__', max_length=2, verbose_name='Этаж, крыло'),
        ),
    ]
